export const TEST_IDS = {
  nav: {
    container: 'site-nav',
    logo: 'nav-logo',
    linkServices: 'nav-link-services',
    linkProcess: 'nav-link-process',
    linkGallery: 'nav-link-gallery',
    linkContact: 'nav-link-contact',
    ctaQuote: 'nav-cta-quote',
    mobileToggle: 'nav-mobile-toggle',
  },
  hero: {
    section: 'hero-section',
    title: 'hero-title',
    subtitle: 'hero-subtitle',
    ctaQuote: 'hero-cta-quote',
    ctaServices: 'hero-cta-services',
    shieldCanvas: 'hero-shield-canvas',
  },
  services: {
    section: 'services-section',
    card: (key) => `service-card-${key}`,
  },
  process: { section: 'process-section' },
  gallery: { section: 'gallery-section' },
  testimonials: { section: 'testimonials-section' },
  quote: {
    section: 'quote-section',
    form: 'quote-form',
    name: 'quote-input-name',
    phone: 'quote-input-phone',
    email: 'quote-input-email',
    vehicle: 'quote-input-vehicle',
    service: 'quote-select-service',
    message: 'quote-input-message',
    submit: 'quote-submit-button',
    success: 'quote-success-message',
  },
  footer: {
    section: 'site-footer',
    instagram: 'footer-instagram',
    phone: 'footer-phone',
    email: 'footer-email',
  },
};
